### ISSUE TITLE
Finding this error in run time !

### ISSUE THREAD

**Issue by chiradeep7** [robbiehaynes/arbitrage-finder#5]
Hi, when i am running arbitrage-finder.py, i am finding this error in run time. Please solve this error.
Traceback (most recent call last):
  File "C:\Users\ASUS\Downloads\arbitrage-finder-main\arbitrage-finder.py", line 33, in <module>
    for filename in os.listdir('odds'):
                    ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'odds'

**Comment by robbiehaynes** [comment]
Hi @chiradeep7, the script expects a folder named 'odds' in the project directory.
the commit 87fac7f solved this issue with a .gitkeep please fetch and pull the latest changes
